import type { BuildingInfo } from '../types/gameData';

export const buildingsData: Record<string, BuildingInfo> = {
  1: {
    id: 1,
    race: "valdari",
    name: "Palace",
    main: true,
    description: "The Palace is the heart of your kingdom.",
    level: 0,
    buildCost: { gold: 1000, supplies: 800 },
    buildTime: 120,
    image: '/images/Valdari/construcciones/palacio.png',
    unitsProduced: [
      {
        id: 1,
        available: 0,
        name: "Men",
        unitType: "poblation",
        cost: { gold: 50, food: 1 },
        buildTime: 20,
        image: '/images/Valdari/poblation/Men.png',
        gif: '',
        special: "Call to Arms",
        skillName: "",
        skillDesc: "",
        skillAction: "none",
        attack: 5.5,
        armor: 0,
        hp: 220,
        mana: 100,
        transportSize: 1,
        carryCapacity: 10,
      },
      {
        id: 2,
        available: 0,
        name: "Woman",
        unitType: "poblation",
        cost: { gold: 50, food: 1 },
        buildTime: 20,
        image: '/images/Valdari/poblation/Woman.png',
        gif: '',
        special: "Call to Arms",
        skillName: "",
        skillDesc: "",
        skillAction: "none",
        attack: 5.5,
        armor: 0,
        hp: 220,
        mana: 100,
        transportSize: 1,
        carryCapacity: 10,
      },
      {
        id: 16,
        available: 0,
        name: "Emisario",
        unitType: "poblation",
        cost: { gold: 50, food: 1 },
        buildTime: 20,
        image: '/images/Valdari/poblation/Emisario.png',
        gif: '',
        special: "Diplomacy",
        skillName: "",
        skillDesc: "",
        skillAction: "none",
        attack: 2.0,
        armor: 0,
        hp: 180,
        mana: 100,
        transportSize: 1,
        carryCapacity: 10,
      }
    ],
    upgradesAvailable: [
      {
        name: "Royal Guard Training",
        cost: { gold: 500, supplies: 200, chrono: 5 },
        time: 60,
        description: "Increases palace defense by 50%"
      },
      {
        name: "Tax Collection",
        cost: { gold: 300, chrono: 10 },
        time: 45,
        description: "Increases gold production by 20%"
      }
    ]
  },
  2: {
    id: 2,
    race: "valdari",
    name: "Farm",
    main: false,
    description: "Produces food for your population.",
    level: 0,
    buildCost: { gold: 300, supplies: 200 },
    buildTime: 45,
    image: '/images/Valdari/construcciones/granja.png',
    unitsProduced: [
      {
        id: 3,
        available: 0,
        name: "Obrero",
        unitType: "unit",
        cost: { gold: 30, food: 1 },
        buildTime: 15,
        image: '/images/Valdari/units/Obrero.png',
        gif: '',
        special: "Construction",
        skillName: "Milicia de Emergencia",
        skillDesc: "Se arma con picos y palas, infligiendo 45 daño a un enemigo aleatorio",
        skillAction: "obrero_strike",
        attack: 3.0,
        armor: 0,
        hp: 150,
        mana: 100,
        transportSize: 1,
        carryCapacity: 50,
      }
    ],
    upgradesAvailable: [
      {
        name: "Improved Irrigation",
        cost: { gold: 150, supplies: 100 },
        time: 30,
        description: "Increases food production by 30%"
      }
    ]
  },
  3: {
    id: 3,
    race: "valdari",
    name: "Barracks",
    main: false,
    description: "Train Footmen, Riflemen, Knights, and Siege Engines here.",
    level: 0,
    buildCost: { gold: 600, supplies: 450 },
    buildTime: 90,
    image: '/images/Valdari/construcciones/cuartel.png',
    unitsProduced: [
      {
        id: 4,
        available: 0,
        name: "Centinela",
        unitType: "unit",
        cost: { gold: 50, food: 1 },
        buildTime: 20,
        image: '/images/Valdari/units/Centinela.png',
        gif: '',
        special: "Guard Duty",
        skillName: "Defend",
        skillDesc: "Defiende aumentando temporalmente la armadura",
        skillAction: "defend",
        attack: 13.0,
        armor: 2,
        hp: 420,
        mana: 200,
        transportSize: 1,
        carryCapacity: 10,
      },
      {
        id: 5,
        available: 0,
        name: "Francotirador",
        unitType: "unit",
        cost: { gold: 75, food: 1 },
        buildTime: 27,
        image: '/images/Valdari/units/Francotirador.png',
        gif: '',
        special: "Precision Shot",
        skillName: "Tiro Certero",
        skillDesc: "80 de daño crítico al enemigo con menos HP",
        skillAction: "sniper_shot",
        attack: 22.0,
        armor: 0,
        hp: 535,
        mana: 200,
        transportSize: 1,
        carryCapacity: 10,
      },
      {
        id: 6,
        available: 0,
        name: "Caballero",
        unitType: "unit",
        cost: { gold: 120, food: 2 },
        buildTime: 40,
        image: '/images/Valdari/units/Caballero.png',
        gif: '',
        special: "Charge",
        skillName: "Spell Immunity",
        skillDesc: "Inmune al daño de habilidades mágicas",
        skillAction: "spell_immunity",
        attack: 33.0,
        armor: 5,
        hp: 800,
        mana: 400,
        transportSize: 2,
        carryCapacity: 10,
      },

    ],
    upgradesAvailable: [
      {
        name: "Defensive Training",
        cost: { gold: 100, supplies: 50 },
        time: 40,
        description: "Increases armor of trained units by 2"
      },
      {
        name: "Long Rifles",
        cost: { gold: 150, supplies: 0, chrono: 5 },
        time: 50,
        description: "Increases range of riflemen by 20%"
      }
    ]
  },
  4: {
    id: 4,
    race: "valdari",
    name: "Temple",
    main: false,
    description: "Train Priests, Sorceresses, and Spell Breakers here.",
    level: 0,
    buildCost: { gold: 500, supplies: 300 },
    buildTime: 80,
    image: '/images/Valdari/construcciones/templo.png',
    unitsProduced: [
      {
        id: 7,
        available: 0,
        name: "Cirujano",
        unitType: "unit",
        cost: { gold: 80, food: 1 },
        buildTime: 30,
        image: '/images/Valdari/units/Cirujano.png',
        gif: '',
        special: "Heal",
        skillName: "Heal",
        skillDesc: "Restaura 80 HP a todos los aliados en batalla",
        skillAction: "priest_heal",
        attack: 11.0,
        armor: 0,
        hp: 290,
        mana: 100,
        transportSize: 1,
        carryCapacity: 10,
      },
      {
        id: 8,
        available: 0,
        name: "Arcanista",
        unitType: "unit",
        cost: { gold: 100, food: 1 },
        buildTime: 30,
        image: '/images/Valdari/units/Arcanista.png',
        gif: '',
        special: "Magic Slow",
        skillName: "Slow",
        skillDesc: "Ralentiza a los enemigos, reduciendo su ataque",
        skillAction: "slow",
        attack: 11.0,
        armor: 0,
        hp: 305,
        mana: 100,
        transportSize: 1,
        carryCapacity: 10,
      },
      {
        id: 9,
        available: 0,
        name: "Disruptor",
        unitType: "unit",
        cost: { gold: 100, food: 1 },
        buildTime: 28,
        image: '/images/Valdari/units/Disruptor.png',
        gif: '',
        special: "Feedback",
        skillName: "Feedback",
        skillDesc: "Drena maná e inflige daño a los enemigos",
        skillAction: "feedback",
        attack: 15.0,
        armor: 3,
        hp: 600,
        mana: 400,
        transportSize: 1,
        carryCapacity: 10,
      }
    ],
    upgradesAvailable: [
      {
        name: "Holy Light",
        cost: { gold: 120, chrono: 10 },
        time: 45,
        description: "Increases healing power of priests by 30%"
      },
      {
        name: "Mana Surge",
        cost: { gold: 150, supplies: 30, chrono: 5 },
        time: 50,
        description: "Reduces mana costs by 20%"
      }
    ]
  },
  5: {
    id: 5,
    race: "valdari",
    name: "Aviary",
    main: false,
    description: "Train Mortar Teams and Gryphon Riders here.",
    level: 0,
    buildCost: { gold: 700, supplies: 500 },
    buildTime: 100,
    image: '/images/Valdari/construcciones/aviary.png',
    unitsProduced: [
      {
        id: 10,
        available: 0,
        name: "Falange",
        unitType: "unit",
        cost: { gold: 90, food: 1 },
        buildTime: 33,
        image: '/images/Valdari/units/Falange.png',
        gif: '',
        special: "Demolition",
        skillName: "Flare",
        skillDesc: "Revela el tablero e inflige daño explosivo",
        skillAction: "flare",
        attack: 59.0,
        armor: 0,
        hp: 360,
        mana: 100,
        transportSize: 1,
        carryCapacity: 10,
      },
      {
        id: 11,
        available: 0,
        name: "Jinetes",
        unitType: "unit",
        cost: { gold: 150, food: 2 },
        buildTime: 45,
        image: '/images/Valdari/units/Jinetes.png',
        gif: '',
        special: "Storm Hammer",
        skillName: "Storm Hammer",
        skillDesc: "Daño en área y encadenamiento",
        skillAction: "storm_hammer",
        attack: 50.0,
        armor: 0,
        hp: 825,
        mana: 400,
        transportSize: 2,
        carryCapacity: 10,
      }
    ],
    upgradesAvailable: [
      {
        name: "Aerial Superiority",
        cost: { gold: 200, supplies: 50, chrono: 8 },
        time: 60,
        description: "Increases flying units' attack by 25%"
      },
      {
        name: "Dive Bomb",
        cost: { gold: 180, supplies: 0 },
        time: 45,
        description: "Adds splash damage to flying attacks"
      }
    ]
  },
  6: {
    id: 6,
    race: "valdari",
    name: "Altar",
    main: false,
    description: "Revive your fallen heroes here.",
    level: 0,
    buildCost: { gold: 800, supplies: 500 },
    buildTime: 110,
    image: '/images/Valdari/construcciones/altar.png',
    unitsProduced: [
      {
        id: 12,
        available: 0,
        name: "Dawnforged",
        unitType: "heroe",
        cost: { gold: 150, food: 2 },
        buildTime: 55,
        image: '/images/Valdari/heroes/Dawnforged.png',
        gif: '',
        special: "Divine Champion",
        skillName: "Holy Light",
        skillDesc: "Cura 150 HP masiva a todos los aliados",
        skillAction: "paladin_aura",
        skillName2: "Divine Shield",
        skillDesc2: "Otorga escudo divino e invulnerabilidad temporal",
        skillAction2: "divine_shield",
        attack: 24.0,
        armor: 3,
        hp: 675,
        mana: 400,
        transportSize: 2,
        carryCapacity: 10,
      },
      {
        id: 13,
        available: 0,
        name: "Arconte",
        unitType: "heroe",
        cost: { gold: 150, food: 2 },
        buildTime: 55,
        image: '/images/Valdari/heroes/Arconte.png',
        gif: '',
        special: "Brilliance Aura",
        skillName: "Blizzard",
        skillDesc: "90 de daño masivo a TODOS los enemigos",
        skillAction: "archmage_blizzard",
        skillName2: "Explosión Arcana",
        skillDesc2: "Inflige 60 daño a 2 enemigos aleatorios reduciendo su armadura en 2",
        skillAction2: "arcane_blast",
        attack: 23.0,
        armor: 1,
        hp: 575,
        mana: 200,
        transportSize: 1,
        carryCapacity: 10,
      },
      {
        id: 14,
        available: 0,
        name: "Thane",
        unitType: "heroe",
        cost: { gold: 150, food: 2 },
        buildTime: 55,
        image: '/images/Valdari/heroes/Thane.png',
        gif: '',
        special: "Avatar of War",
        skillName: "Storm Bolt",
        skillDesc: "150 de daño devastador a un solo enemigo",
        skillAction: "mountain_king_avatar",
        skillName2: "Thunder Clap",
        skillDesc2: "Golpea el suelo infligiendo daño en área",
        skillAction2: "thunder_clap",
        attack: 31.0,
        armor: 4,
        hp: 725,
        mana: 400,
        transportSize: 2,
        carryCapacity: 10,
      },
      {
        id: 15,
        available: 0,
        name: "Vastago",
        unitType: "heroe",
        cost: { gold: 150, food: 2 },
        buildTime: 55,
        image: '/images/Valdari/heroes/Vastago.png',
        gif: '',
        special: "Phoenix Fire",
        skillName: "Flame Strike",
        skillDesc: "100 de daño de fuego a 3 enemigos aleatorios",
        skillAction: "bloodmage_flamestrike",
        skillName2: "Banish",
        skillDesc2: "Envía al plano astral reduciendo defensas del objetivo",
        skillAction2: "banish",
        attack: 22.0,
        armor: 1,
        hp: 500,
        mana: 200,
        transportSize: 1,
        carryCapacity: 10,
      }
    ],
    upgradesAvailable: [
      {
        name: "Resurrection",
        cost: { gold: 250, chrono: 15 },
        time: 90,
        description: "Reduces hero revival time by 50%"
      },
      {
        name: "Divine Shield",
        cost: { gold: 300, supplies: 0, chrono: 10 },
        time: 60,
        description: "Gives heroes temporary invulnerability"
      }
    ]
  },
  7: {
    id: 7,
    race: "valdari",
    name: "Market",
    main: false,
    description: "Trade resources and buy items here.",
    level: 0,
    buildCost: { gold: 400, supplies: 300 },
    buildTime: 60,
    image: '/images/Valdari/construcciones/mercado.png',
    unitsProduced: [],
    upgradesAvailable: [
      {
        name: "Activar BOT",
        cost: { gold: 500, chrono: 10 },
        time: 5,
        description: "Activa el algoritmo de trading automático (BOT) para operar en el mercado."
      },
      {
        name: "Subir Lotaje",
        cost: { gold: 300, chrono: 5 },
        time: 10,
        description: "Aumenta el tamaño de la posición (lotes) de las operaciones del BOT."
      }
    ]
  }
};
