const fs = require('fs');

const dataPath = 'src/data/data.json';
const data = JSON.parse(fs.readFileSync(dataPath));

const gorkarBuildings = [
  {
    "Race": "gorkar",
    "Name": "BloodHall",
    "Img": "/images/GorKar/construcciones/BloodHall.png",
    "Gold": "1000",
    "Wood": "500",
    "Stone": "300",
    "Time": "120",
    "Hit Points": "1500",
    "Food": "10",
    "Builds": "PEON",
    "Requisito": "null",
    "Type": "Structure",
    "Damage": "0",
    "Range": "0",
    "Cooldown": "0"
  },
  {
    "Race": "gorkar",
    "Name": "WarHut",
    "Img": "/images/GorKar/construcciones/WarHut.png",
    "Gold": "400",
    "Wood": "150",
    "Stone": "0",
    "Time": "60",
    "Hit Points": "1200",
    "Food": "0",
    "Builds": "Berserker, Cazacabezas",
    "Requisito": "BloodHall",
    "Type": "Structure",
    "Damage": "0",
    "Range": "0",
    "Cooldown": "0"
  },
  {
    "Race": "gorkar",
    "Name": "ShamanTent",
    "Img": "/images/GorKar/construcciones/ShamanTent.png",
    "Gold": "350",
    "Wood": "250",
    "Stone": "50",
    "Time": "60",
    "Hit Points": "800",
    "Food": "0",
    "Builds": "Chaman, Invocador",
    "Requisito": "BloodHall",
    "Type": "Structure",
    "Damage": "0",
    "Range": "0",
    "Cooldown": "0"
  },
  {
    "Race": "gorkar",
    "Name": "HuntCamp",
    "Img": "/images/GorKar/construcciones/HuntCamp.png",
    "Gold": "450",
    "Wood": "300",
    "Stone": "100",
    "Time": "70",
    "Hit Points": "1000",
    "Food": "0",
    "Builds": "Raider, Rompehueso, Vigía",
    "Requisito": "BloodHall",
    "Type": "Structure",
    "Damage": "0",
    "Range": "0",
    "Cooldown": "0"
  },
  {
    "Race": "gorkar",
    "Name": "SkyPerch",
    "Img": "/images/GorKar/construcciones/SkyPerch.png",
    "Gold": "500",
    "Wood": "400",
    "Stone": "150",
    "Time": "80",
    "Hit Points": "1100",
    "Food": "0",
    "Builds": "Jinete",
    "Requisito": "BloodHall",
    "Type": "Structure",
    "Damage": "0",
    "Range": "0",
    "Cooldown": "0"
  },
  {
    "Race": "gorkar",
    "Name": "TotemCircle",
    "Img": "/images/GorKar/construcciones/TotemCircle.png",
    "Gold": "600",
    "Wood": "300",
    "Stone": "200",
    "Time": "90",
    "Hit Points": "1300",
    "Food": "0",
    "Builds": "Gorruk, Kargath, Urzok, Valka",
    "Requisito": "BloodHall",
    "Type": "Structure",
    "Damage": "0",
    "Range": "0",
    "Cooldown": "0"
  },
  {
    "Race": "gorkar",
    "Name": "TradeHut",
    "Img": "/images/GorKar/construcciones/TradeHut.png",
    "Gold": "400",
    "Wood": "200",
    "Stone": "100",
    "Time": "60",
    "Hit Points": "800",
    "Food": "0",
    "Builds": "null",
    "Requisito": "BloodHall",
    "Type": "Structure",
    "Damage": "0",
    "Range": "0",
    "Cooldown": "0"
  },
  {
    "Race": "gorkar",
    "Name": "BoneWatch",
    "Img": "/images/GorKar/construcciones/BoneWatch.png",
    "Gold": "450",
    "Wood": "150",
    "Stone": "300",
    "Time": "70",
    "Hit Points": "600",
    "Armor": "3",
    "Food": "0",
    "Builds": "null",
    "Requisito": "BloodHall",
    "Type": "Structure",
    "Damage": "15",
    "Range": "700",
    "Cooldown": "1.0"
  }
];

const gorkarUnits = [
  {
    "Race": "gorkar",
    "Name": "PEON",
    "Img": "/images/GorKar/poblation/Goblin.png",
    "Gold": "50",
    "Wood": "0",
    "Stone": "0",
    "Time": "15",
    "Hit Points": "250",
    "Armor": "0",
    "Food": "1",
    "Builds": "Construction",
    "Requisito": "BloodHall",
    "Type": "poblation",
    "Damage": "5",
    "Range": "0",
    "Cooldown": "1.5"
  },
  {
    "Race": "gorkar",
    "Name": "Berserker",
    "Img": "/images/GorKar/units/Berserker.png",
    "Gold": "200",
    "Wood": "0",
    "Stone": "0",
    "Time": "30",
    "Hit Points": "700",
    "Armor": "1",
    "Food": "1",
    "Builds": "null",
    "Requisito": "WarHut",
    "Type": "unit",
    "Damage": "25",
    "Range": "0",
    "Cooldown": "1.5"
  },
  {
    "Race": "gorkar",
    "Name": "Cazacabezas",
    "Img": "/images/GorKar/units/Cazacabezas.png",
    "Gold": "135",
    "Wood": "20",
    "Stone": "0",
    "Time": "20",
    "Hit Points": "350",
    "Armor": "0",
    "Food": "1",
    "Builds": "null",
    "Requisito": "WarHut",
    "Type": "unit",
    "Damage": "20",
    "Range": "400",
    "Cooldown": "1.3"
  },
  {
    "Race": "gorkar",
    "Name": "Chaman",
    "Img": "/images/GorKar/units/Chaman.png",
    "Gold": "130",
    "Wood": "20",
    "Stone": "0",
    "Time": "30",
    "Hit Points": "305",
    "Armor": "0",
    "Food": "1",
    "Builds": "null",
    "Requisito": "ShamanTent",
    "Type": "unit",
    "Damage": "11",
    "Range": "500",
    "Cooldown": "2.0"
  },
  {
    "Race": "gorkar",
    "Name": "Invocador",
    "Img": "/images/GorKar/units/Invocador.png",
    "Gold": "145",
    "Wood": "25",
    "Stone": "0",
    "Time": "30",
    "Hit Points": "265",
    "Armor": "0",
    "Food": "1",
    "Builds": "null",
    "Requisito": "ShamanTent",
    "Type": "unit",
    "Damage": "11",
    "Range": "500",
    "Cooldown": "2.0"
  },
  {
    "Race": "gorkar",
    "Name": "Machacador",
    "Img": "/images/GorKar/units/Machacador.png",
    "Gold": "280",
    "Wood": "80",
    "Stone": "0",
    "Time": "55",
    "Hit Points": "1300",
    "Armor": "2",
    "Food": "2",
    "Builds": "null",
    "Requisito": "HuntCamp",
    "Type": "unit",
    "Damage": "41",
    "Range": "0",
    "Cooldown": "1.5"
  },
  {
    "Race": "gorkar",
    "Name": "Jinete",
    "Img": "/images/GorKar/units/Jinete.png",
    "Gold": "265",
    "Wood": "40",
    "Stone": "0",
    "Time": "40",
    "Hit Points": "570",
    "Armor": "0",
    "Food": "2",
    "Builds": "null",
    "Requisito": "SkyPerch",
    "Type": "unit",
    "Damage": "40",
    "Range": "450",
    "Cooldown": "1.4"
  },
  {
    "Race": "gorkar",
    "Name": "Raider",
    "Img": "/images/GorKar/units/Raider.png",
    "Gold": "180",
    "Wood": "40",
    "Stone": "0",
    "Time": "28",
    "Hit Points": "610",
    "Armor": "1",
    "Food": "1",
    "Builds": "null",
    "Requisito": "HuntCamp",
    "Type": "unit",
    "Damage": "22",
    "Range": "0",
    "Cooldown": "1.3"
  },
  {
    "Race": "gorkar",
    "Name": "Rompehueso",
    "Img": "/images/GorKar/units/Rompehueso.png",
    "Gold": "220",
    "Wood": "50",
    "Stone": "0",
    "Time": "40",
    "Hit Points": "425",
    "Armor": "0",
    "Food": "1",
    "Builds": "null",
    "Requisito": "HuntCamp",
    "Type": "unit",
    "Damage": "100",
    "Range": "800",
    "Cooldown": "3.5"
  },
  {
    "Race": "gorkar",
    "Name": "Vigía",
    "Img": "/images/GorKar/units/Vigía.png",
    "Gold": "255",
    "Wood": "60",
    "Stone": "0",
    "Time": "40",
    "Hit Points": "1000",
    "Armor": "1",
    "Food": "2",
    "Builds": "null",
    "Requisito": "HuntCamp",
    "Type": "unit",
    "Damage": "30",
    "Range": "0",
    "Cooldown": "1.5"
  },
  {
    "Race": "gorkar",
    "Name": "Gorruk",
    "Img": "/images/GorKar/heroes/Gorruk.png",
    "Gold": "300",
    "Wood": "50",
    "Stone": "0",
    "Time": "55",
    "Hit Points": "575",
    "Armor": "3",
    "Food": "2",
    "Builds": "null",
    "Requisito": "TotemCircle",
    "Type": "heroe",
    "Damage": "29",
    "Range": "0",
    "Cooldown": "1.2"
  },
  {
    "Race": "gorkar",
    "Name": "Kargath",
    "Img": "/images/GorKar/heroes/Kargath.png",
    "Gold": "300",
    "Wood": "50",
    "Stone": "0",
    "Time": "55",
    "Hit Points": "500",
    "Armor": "1",
    "Food": "2",
    "Builds": "null",
    "Requisito": "TotemCircle",
    "Type": "heroe",
    "Damage": "24",
    "Range": "500",
    "Cooldown": "1.5"
  },
  {
    "Race": "gorkar",
    "Name": "Urzok",
    "Img": "/images/GorKar/heroes/Urzok.png",
    "Gold": "300",
    "Wood": "50",
    "Stone": "0",
    "Time": "55",
    "Hit Points": "700",
    "Armor": "3",
    "Food": "2",
    "Builds": "null",
    "Requisito": "TotemCircle",
    "Type": "heroe",
    "Damage": "31",
    "Range": "0",
    "Cooldown": "1.5"
  },
  {
    "Race": "gorkar",
    "Name": "Valka",
    "Img": "/images/GorKar/heroes/Valka.png",
    "Gold": "300",
    "Wood": "50",
    "Stone": "0",
    "Time": "55",
    "Hit Points": "575",
    "Armor": "1",
    "Food": "2",
    "Builds": "null",
    "Requisito": "TotemCircle",
    "Type": "heroe",
    "Damage": "24",
    "Range": "400",
    "Cooldown": "1.5"
  }
];

// Append GorKar to the respective arrays if not already present
let changed = false;

if (!data.building.some(b => b.Race === 'gorkar')) {
  data.building.push(...gorkarBuildings);
  changed = true;
}

if (!data.Unit.some(u => u.Race === 'gorkar')) {
  data.Unit.push(...gorkarUnits);
  changed = true;
}

if (changed) {
  fs.writeFileSync(dataPath, JSON.stringify(data, null, 2));
  console.log('Successfully appended GorKar data.');
} else {
  console.log('GorKar data already exists.');
}
